### PR TITLE
add-chinese-translation

### PR DESCRIPTION
**Pull request by chenkeao**
add chinese translation

### CODE REVIEW

**Comment by DavidLazarescu** [comment]
Thanks for your contribution! While testing the translation, I noticed that you did not translate: "On", "Off", "Light", "Dark" and "Include new lines in copied text", I have translated these to: "开", "开", "明亮", "黑暗" and "在复制的文本中包含新行" respectively. Is that correct, or would you change any of my translations?

**Comment by DavidLazarescu** [comment]
I have created a new PR from your repo which correctly requests to merge into dev/develop instead of main. Lets move our conversation there.

**Comment by chenkeao** [comment]
I'm sorry, some translations were overlooked by me. Please note: "Off"="关",
everything else is fine. I really like Librum, and I look forward to your
improvements on it.

David Lazarescu ***@***.***> 於 2023年12月12日週二 上午2:08寫道：

**Comment by DavidLazarescu** [comment]
Thanks, I have corrected it!

**Pull request closed without merging**
