### PR TITLE
Add Ukranian translation

### PR DESCRIPTION
**Pull request by MrOnlineCoder**
- Added Ukranian translation in .ts file to `/src/presentation`
- Added 'uk' record in Language Model
- Added .ts file to CMakeLists

Open questions:
- Not sure about the translation for Home page - didn't come up with a better name rather than Початок (which means "Start" or "Beginning") - wanted to know if it would be fine to rename this to "Library" instead? Which is actually making more sense, at least for me

Managed to compile and run app on MacOS, example screenshots with translations:

Screenshot 2023-12-21 at 23 54 33
Screenshot 2023-12-21 at 23 54 50
Screenshot 2023-12-21 at 23 55 23
Screenshot 2023-12-21 at 23 55 57
Screenshot 2023-12-21 at 23 56 13

### CODE REVIEW

**Comment by DavidLazarescu** [comment]
Thanks for the great PR. Please make sure that the translation is relatively similar in length to the original english version.
Testing your translations I have found some problems, as e.g. in the following:
image
image
image

**Comment by MrOnlineCoder** [comment]
@DavidLazarescu I've tried to match it at first, and it looked fine on my side. Seems it's related to us having different resolutions/window sizes? I will try to rephrase the translations
Screenshot 2023-12-22 at 14 51 08
Screenshot 2023-12-22 at 14 51 26

**Comment by MrOnlineCoder** [comment]
@DavidLazarescu please take a look now. The account upgrade popup unfortunately is not fixed, I cannot find a shorter translation for that. Maybe it's possible just to enlarge these popups a bit, so no issue with such and other translations would occur?

**Comment by DavidLazarescu** [comment]
Wouldn't it be possible to change the popup title to simply "Upgrade" instead of "Improve your account"?

**Comment by DavidLazarescu** [comment]
Also, there still is a problem with the following:
image
image

**Comment by MrOnlineCoder** [comment]
@DavidLazarescu thanks for noticing, pushed some fixes (changed respective translations of):

- Changed "Improve your account" to literal "Upgrade"
- "Manage tags" is now "Change tags"
- "Remove book" is just now "Remove"
- "Rename" in bookmarks is now "Edit title" (shortened)

**Comment by DavidLazarescu** [comment]
Thanks for fixing the issues I pointed out above, I still found these:
image
image
image

Once these are fixed, I think that it should be read to be merged into the project.

**Comment by MrOnlineCoder** [comment]
@DavidLazarescu I've added fix to "Manage profile" string.
Unfortunately, I cannot find a way to shorten the "Save to files" translation, I guess maybe we can leave it as-is with 3 dots at end or just increase the popup menu width a bit? Only option is "To files" ("У файли") which may not be clear to the user.

"Free books" translation is not also easily solveable, there is no context-saving short synonym for word "free", rather than "безкоштовний" or "безплатний". My only suggestion is to, again, modify the length of the sidebar, maybe make it "shrink" to fit the width of menu items, or shorten it as "Безк. книги" or "Безкоштовні", where in first variant the word "Free" is shortened, and in second the word "books" is omitted. Don't know if it would be clear enough for the user. 

Thanks.

**Comment by DavidLazarescu** [comment]
Thanks for the detailed explanation!

**Comment by DavidLazarescu** [comment]
Hey @MrOnlineCoder, we have just added a big new feature that needs to be translated. It would be great if you could download https://github.com/Librum-Reader/Librum/blob/dev/develop/src/presentation/translations/librum_uk.ts, fill out the few new words and create a PR with the new file.

**Comment by DavidLazarescu** [comment]
Great, we'll probably publish the new version tomorrow evening, if its done by then we can still get it into the 0.12 release, else we'll add it to 0.12.1.

**Comment by DavidLazarescu** [comment]
Hey @MrOnlineCoder! We are preparing another release. It would be great if you could download https://github.com/Librum-Reader/Librum/blob/dev/develop/src/presentation/translations/librum_uk.ts, fill out the few new words and create a PR with the new file :smile:

**Comment by MrOnlineCoder** [comment]
Hey @DavidLazarescu, would be happy to help! Will try to complete it today / tomorrow

**Pull request merged**
