### PR TITLE
Added Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by smrsassa**
I appreciate your time in reviewing this pull request. Please feel free to provide feedback, and I'm open to making any necessary adjustments.

### CODE REVIEW

**Comment by DavidLazarescu** [comment]
Hey, thanks for the PR, it looks great. I'll just need to check that everything is ok visually. Apart of that, please change this PR to request merging into dev/develop instead of main

**Comment by smrsassa** [comment]
Ok, i will keep them closer in length.

**Comment by DavidLazarescu** [comment]
Much better, but there still are some problems:
image
image
image

**Comment by smrsassa** [comment]
- First case:
We have the word "Só" which is a more informal way to translate "Only". I believe this is the only option with fewer characters in the Portuguese translation. If you find a more informal option undesirable, I could simply use "Livros" which would be equivalent to just "Books". Which alternative do you think is better?

- Second case:
For "Detalhes do livro" I would choose to use only "Detalhes" which means "Details". I understand that it's already intuitive enough.
"Marcar como livro" I will leave as "Marcar c/ livro." It's not a common abbreviation, but we can use it confidently.

- Third case:
I will choose to use "Diferenciar maiúsculas e minúsculas". I believe the space in the difference between "maiúsculas/minúsculas" and "maiúsculas e minúsculas" will be sufficient for the interface to automatically break the line. I saw the translation into German, and the text is long, but the line break is performed.

**Comment by smrsassa** [comment]
> * First case:
>   We have the word "Só" which is a more informal way to translate "Only". I believe this is the only option with fewer characters in the Portuguese translation. If you find a more informal option undesirable, I could simply use "Livros" which would be equivalent to just "Books". Which alternative do you think is better?
> * Second case:
>   For "Detalhes do livro" I would choose to use only "Detalhes" which means "Details". I understand that it's already intuitive enough.
>   "Marcar como lido" I will leave as "Marcar c/ lido." It's not a common abbreviation, but we can use it confidently.
> * Third case:
>   I will choose to use "Diferenciar maiúsculas e minúsculas". I believe the space in the difference between "maiúsculas/minúsculas" and "maiúsculas e minúsculas" will be sufficient for the interface to automatically break the line. I saw the translation into German, and the text is long, but the line break is performed.
> 
> After receiving your feedback, I do the commit.

**Comment by DavidLazarescu** [comment]
- First case: I think only using "Livros" is good enough

The rest sounds good as you described it.

**Comment by DavidLazarescu** [comment]
Ok, the last things I found are the following:
image
image

If you make a commit with these two shortened, I'll be able to merge it into dev/develop.

**Comment by DavidLazarescu** [comment]
Hey @smrsassa, we have just added a new feature that needs to be translated. It would be great if you could download https://github.com/Librum-Reader/Librum/blob/dev/develop/src/presentation/translations/librum_pt.ts, fill out the few new words and create a PR with the new file.

**Pull request merged**
