### PR TITLE
Added Indonesian translation

### PR DESCRIPTION
**Pull request by snowfluke**

### CODE REVIEW

**Comment by DavidLazarescu** [comment]
Thanks, this looks great. I'll check if everything fits visually soon. Could you please change the PR to request a merge into dev/develop instead of main?

**Comment by DavidLazarescu** [comment]
Hey @snowfluke, we have just added a new feature that needs to be translated. It would be great if you could download https://github.com/Librum-Reader/Librum/blob/dev/develop/src/presentation/translations/librum_id.ts, fill out the few new words and create a PR with the new file.

**Comment by DavidLazarescu** [comment]
Hey, have you already submitted a PR for this? I was not able to find anything while checking the status of the translations.

**Comment by snowfluke** [comment]
Sorry for late, just submitted the PR

**Pull request merged**
