### PR TITLE
Fixed shortcut

### PR DESCRIPTION
**Pull request by 1250890838**
Fixed **Shift+Number** shortcut error

### CODE REVIEW

**Comment by 1250890838** [comment]
hello

**Comment by DavidLazarescu** [comment]
Hey, thanks for the PR. I'm quite busy at the moment but I'll take a look and merge it soon.

**Comment by DavidLazarescu** [comment]
Please adapt it to the latest changes of dev/develop to fix the conflicts (the UI pages just moved into a "desktop" subfolder)

**Comment by 1250890838** [comment]
What should I do specifically, create a new pull request?

**Comment by DavidLazarescu** [comment]
No need to create a new one. You can also just update this PR. But if it's easier to create a new one, go for it.

**Pull request closed without merging**
