### PR TITLE
Add chinese translation

### PR DESCRIPTION
**Pull request by DavidLazarescu**

### CODE REVIEW

**Comment by DavidLazarescu** [comment]
Hey @chenkeao, would you be available for continuing to translate some sentences to Chinese from time to time when we add new content to Librum?

**Comment by chenkeao** [comment]
Certainly, as long as I have the time, I'm willing to continue adding and
improving the Chinese translations for Librum.

David Lazarescu ***@***.***> 於 2023年12月15日週五 下午11:47寫道：

**Comment by DavidLazarescu** [comment]
I'm glad to hear that. Would you like to continue in this thread or would you prefer another form of communication? The following text was added for version 0.10.3:
- Book already exists
- It looks like this book already exists in your library:
- Are you sure you that want to add it again?
- Don't add
- Uninstall books
- Delete books

Once we got these for the chinese translation, we can start publishing the new version.

**Comment by chenkeao** [comment]
Here is the translation:
Book already exists=书籍已存在
It looks like this book already exists in your library:=看起来这本书已经在您的书库中：
Are you sure you that want to add it again?=您确定想再次添加这本书吗？
Don't add=不添加
Uninstall books=卸载此书
Delete books=删除此书

Note: Some translations may not be accurate because I don't know the
context, and I will continue to optimize them in the future.

David Lazarescu ***@***.***> 于 2023年12月16日周六 20:01写道：

**Comment by DavidLazarescu** [comment]
Hey @chenkeao, we have just added a new feature that needs to be translated. It would be great if you could download https://github.com/Librum-Reader/Librum/blob/dev/develop/src/presentation/translations/librum_zh.ts, fill out the few new words and create a PR with the new file.

**Pull request merged**
